<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXb77rjl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXb77rjl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXb77rjl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXb77rjl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXb77rjl\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xb77rjl',
    'container.build_id' => '162b0c4b',
    'container.build_time' => 1517668565,
));
