<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container11fyhcx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container11fyhcx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container11fyhcx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container11fyhcx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container11fyhcx\appProdProjectContainer(array(
    'container.build_hash' => '11fyhcx',
    'container.build_id' => 'afab16e5',
    'container.build_time' => 1517665305,
));
